### ISSUE TITLE
Download backup not working

### ISSUE THREAD

**Issue by RaefWolfe** [sawprogramming/WoW-Raid-Manager#58]
Title. Clicking the button doesn't seem to do anything. Tried in multiple browsers.

**Comment by sawprogramming** [comment]
I'll check it if I get time this weekend. It might just be a slow process that doesn't give any feedback as to what it is doing. Did you see any network logs from the browser (or console errors)?

**Comment by sawprogramming** [comment]
Works fine on my local copy. If there is an error, it would be in `/path-to-your-server-installation/logs/php_error.log`.

**Comment by RaefWolfe** [comment]
Failed to load resource: the server responded with a status of 500 ()
angular.min.js?ver=5.3.2:93 GET [[[[websiteurl]]]]/wp-admin/admin-ajax.php?action=wro_backup_dl 500
(anonymous) @ angular.min.js?ver=5.3.2:93
p @ angular.min.js?ver=5.3.2:89
g @ angular.min.js?ver=5.3.2:86
(anonymous) @ angular.min.js?ver=5.3.2:119
$eval @ angular.min.js?ver=5.3.2:133
$digest @ angular.min.js?ver=5.3.2:130
$apply @ angular.min.js?ver=5.3.2:133
(anonymous) @ angular.min.js?ver=5.3.2:254
dispatch @ jquery-2.1.3.min.js?ver=5.3.2:3
r.handle @ jquery-2.1.3.min.js?ver=5.3.2:3

**Comment by RaefWolfe** [comment]
I got my host guy to fix it :P Thanks.

**Comment by daniel-widrick** [comment]
`  thrown in /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/database/DatabaseExporter.php on line 31
[21-Jan-2020 12:02:16 America/New_York] PHP Fatal error:  Uncaught Exception: Unable to retrieve access token for API. in /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/WowAPI.php:90
Stack trace:
#0 /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/WowAPI.php(76): WRO\WowApi->GetOAuthToken()
#1 /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/WowAPI.php(57): WRO\WowApi->GetSuffix()
#2 /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/services/RealmService.php(22): WRO\WowApi->GetRealmList()
#3 /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/wrm.php(112): WRO\Services\RealmService->UpdateRealmList()
#4 /var/www/modguild/wp-includes/class-wp-hook.php(288): WRO\WRO::UpdateRealmList()
#5 /var/www/modguild/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters()
#6 /var/www/modguild/wp-includes/plugin.php(544): WP_Hook->do_action()
#7 /var/www/modguild/wp-cron.php(138): do_action_ref_array()
#8 /var/www/modguild/wp-includes/cron.php(683): include_once('/var/www/modgui...')
#9 /var/www/modguild/wp-includes/cron.php(772): spawn_cron()
#10 /var in /var/www/modguild/wp-content/plugins/WoWRaidOrganizer/WowAPI.php on line 90`

Needed `extension=zip`  in `php.ini`
